version: 2
updates:
  # 通常の依存アップデート（週次）
  # すべての依存パッケージ（直接・間接）を毎週チェックし、アップデートPRを作成
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"
