version: 2
updates:
  # 通常の依存アップデート（週次）
  # すべての依存パッケージ（直接・間接）を毎週チェックし、アップデートPRを作成
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    allow:
      - dependency-type: "all"

  # セキュリティアップデートのみ（毎日チェック）
  # セキュリティ関連のアップデートがあれば即日PRを作成
  # すべての依存パッケージ（直接・間接）が対象
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix"
      include: "scope"
    allow:
      - dependency-type: "all"
    labels:
      - "security"
    security-updates-only: true
