// Mocks generated by Mockito 5.4.6 from annotations
// in kiwi/test/providers/ai_correction_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:kiwi/models/ai_correction_model.dart' as _i4;
import 'package:kiwi/services/ai_correction_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AiCorrectionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAiCorrectionService extends _i1.Mock
    implements _i2.AiCorrectionService {
  MockAiCorrectionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.AiCorrection>> fetchAiCorrections({
    required String? diaryEntryId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchAiCorrections, [], {
              #diaryEntryId: diaryEntryId,
            }),
            returnValue: _i3.Future<List<_i4.AiCorrection>>.value(
              <_i4.AiCorrection>[],
            ),
          )
          as _i3.Future<List<_i4.AiCorrection>>);

  @override
  _i3.Future<_i4.AiCorrection?> fetchAiCorrection(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchAiCorrection, [id]),
            returnValue: _i3.Future<_i4.AiCorrection?>.value(),
          )
          as _i3.Future<_i4.AiCorrection?>);

  @override
  _i3.Future<void> insertAiCorrection(_i4.AiCorrection? correction) =>
      (super.noSuchMethod(
            Invocation.method(#insertAiCorrection, [correction]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateAiCorrection(
    String? id,
    _i4.AiCorrection? correction,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateAiCorrection, [id, correction]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAiCorrection(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAiCorrection, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
