// Mocks generated by Mockito 5.4.6 from annotations
// in kiwi/test/providers/user_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:kiwi/models/profile_model.dart' as _i4;
import 'package:kiwi/services/user_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i2.UserService {
  MockUserService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Profile?> fetchUser(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUser, [id]),
            returnValue: _i3.Future<_i4.Profile?>.value(),
          )
          as _i3.Future<_i4.Profile?>);

  @override
  _i3.Future<List<_i4.Profile>> fetchUsers() =>
      (super.noSuchMethod(
            Invocation.method(#fetchUsers, []),
            returnValue: _i3.Future<List<_i4.Profile>>.value(<_i4.Profile>[]),
          )
          as _i3.Future<List<_i4.Profile>>);

  @override
  _i3.Future<void> insertUser(_i4.Profile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#insertUser, [profile]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateUser(String? id, _i4.Profile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [id, profile]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteUser(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
