name: english_diary_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  supabase_flutter: ^2.9.1
  google_sign_in: ^6.3.0
  sentry_flutter: ^9.0.0
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  logger: ^2.5.0
  collection: ^1.19.1
  table_calendar: ^3.2.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.5.3
  mockito: ^5.4.4
  fake_async: ^1.3.1

flutter:

  uses-material-design: true
  assets:
    - .env