name: kiwi
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  supabase_flutter: ^2.9.1
  google_sign_in: ^6.3.0
  sentry_flutter: ^9.0.0
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  logger: ^2.5.0
  collection: ^1.19.1
  table_calendar: ^3.2.0
  intl: ^0.20.2
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.5.3
  mockito: ^5.4.4
  fake_async: ^1.3.1
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true
  assets:
    - .env
    - assets/app-logo.png
    - assets/app-logo-white-bg.png
    - assets/app-logo-android.png
    - assets/app-logo-android-white-bg.png
    - assets/google-web-light-rd-na@4x.png

# アプリアイコン設定
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  # iOSとAndroidで異なる画像を使用
  image_path_android: "assets/app-logo-android-white-bg.png"
  image_path_ios: "assets/app-logo-white-bg.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/app-logo-android-white-bg.png"
  remove_alpha_ios: true

# スプラッシュスクリーン設定
flutter_native_splash:
  color: "#FFFFFF"
  # iOSとAndroidで異なる画像を使用
  image: "assets/app-logo-white-bg.png"  # iOS用
  image_android: "assets/app-logo-android-white-bg.png"  # Android用
  color_dark: "#FFFFFF"
  image_dark: "assets/app-logo-white-bg.png"  # iOS用（ダークモード）
  image_dark_android: "assets/app-logo-android-white-bg.png"  # Android用（ダークモード）
  android_gravity: center
  ios_content_mode: center
  android_12:
    image: "assets/app-logo-android-white-bg.png"
    color: "#FFFFFF"
