// Mocks generated by Mockito 5.4.6 from annotations
// in kiwi/test/services/diary_feedback_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:kiwi/models/diary_feedback_model.dart' as _i5;
import 'package:kiwi/repositories/api_repository.dart' as _i2;
import 'package:kiwi/repositories/diary_feedback_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiRepository_0 extends _i1.SmartFake implements _i2.ApiRepository {
  _FakeApiRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DiaryFeedbackRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDiaryFeedbackRepository extends _i1.Mock
    implements _i3.DiaryFeedbackRepository {
  MockDiaryFeedbackRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiRepository get apiRepository =>
      (super.noSuchMethod(
            Invocation.getter(#apiRepository),
            returnValue: _FakeApiRepository_0(
              this,
              Invocation.getter(#apiRepository),
            ),
          )
          as _i2.ApiRepository);

  @override
  _i4.Future<List<_i5.DiaryFeedback>> fetchDiaryFeedbacks({
    required String? diaryEntryId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchDiaryFeedbacks, [], {
              #diaryEntryId: diaryEntryId,
            }),
            returnValue: _i4.Future<List<_i5.DiaryFeedback>>.value(
              <_i5.DiaryFeedback>[],
            ),
          )
          as _i4.Future<List<_i5.DiaryFeedback>>);

  @override
  _i4.Future<_i5.DiaryFeedback?> fetchDiaryFeedback(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchDiaryFeedback, [id]),
            returnValue: _i4.Future<_i5.DiaryFeedback?>.value(),
          )
          as _i4.Future<_i5.DiaryFeedback?>);

  @override
  _i4.Future<void> insertDiaryFeedback(_i5.DiaryFeedback? feedback) =>
      (super.noSuchMethod(
            Invocation.method(#insertDiaryFeedback, [feedback]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateDiaryFeedback(
    String? id,
    _i5.DiaryFeedback? feedback,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateDiaryFeedback, [id, feedback]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteDiaryFeedback(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDiaryFeedback, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
