// Mocks generated by Mockito 5.4.6 from annotations
// in kiwi/test/services/plan_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:kiwi/models/plan_model.dart' as _i5;
import 'package:kiwi/repositories/api_repository.dart' as _i2;
import 'package:kiwi/repositories/plan_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiRepository_0 extends _i1.SmartFake implements _i2.ApiRepository {
  _FakeApiRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PlanRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlanRepository extends _i1.Mock implements _i3.PlanRepository {
  MockPlanRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiRepository get apiRepository =>
      (super.noSuchMethod(
            Invocation.getter(#apiRepository),
            returnValue: _FakeApiRepository_0(
              this,
              Invocation.getter(#apiRepository),
            ),
          )
          as _i2.ApiRepository);

  @override
  _i4.Future<List<_i5.Plan>> fetchPlans() =>
      (super.noSuchMethod(
            Invocation.method(#fetchPlans, []),
            returnValue: _i4.Future<List<_i5.Plan>>.value(<_i5.Plan>[]),
          )
          as _i4.Future<List<_i5.Plan>>);

  @override
  _i4.Future<_i5.Plan?> fetchPlan(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPlan, [id]),
            returnValue: _i4.Future<_i5.Plan?>.value(),
          )
          as _i4.Future<_i5.Plan?>);

  @override
  _i4.Future<void> insertPlan(_i5.Plan? plan) =>
      (super.noSuchMethod(
            Invocation.method(#insertPlan, [plan]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updatePlan(int? id, _i5.Plan? plan) =>
      (super.noSuchMethod(
            Invocation.method(#updatePlan, [id, plan]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deletePlan(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePlan, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
