// Mocks generated by Mockito 5.4.6 from annotations
// in kiwi/test/services/subscription_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:kiwi/models/subscription_model.dart' as _i5;
import 'package:kiwi/repositories/api_repository.dart' as _i2;
import 'package:kiwi/repositories/subscription_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiRepository_0 extends _i1.SmartFake implements _i2.ApiRepository {
  _FakeApiRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SubscriptionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubscriptionRepository extends _i1.Mock
    implements _i3.SubscriptionRepository {
  MockSubscriptionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiRepository get apiRepository =>
      (super.noSuchMethod(
            Invocation.getter(#apiRepository),
            returnValue: _FakeApiRepository_0(
              this,
              Invocation.getter(#apiRepository),
            ),
          )
          as _i2.ApiRepository);

  @override
  _i4.Future<List<_i5.Subscription>> fetchSubscriptions({
    required String? profileId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchSubscriptions, [], {#profileId: profileId}),
            returnValue: _i4.Future<List<_i5.Subscription>>.value(
              <_i5.Subscription>[],
            ),
          )
          as _i4.Future<List<_i5.Subscription>>);

  @override
  _i4.Future<_i5.Subscription?> fetchSubscription(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchSubscription, [id]),
            returnValue: _i4.Future<_i5.Subscription?>.value(),
          )
          as _i4.Future<_i5.Subscription?>);

  @override
  _i4.Future<void> insertSubscription(_i5.Subscription? subscription) =>
      (super.noSuchMethod(
            Invocation.method(#insertSubscription, [subscription]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateSubscription(
    int? id,
    _i5.Subscription? subscription,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateSubscription, [id, subscription]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteSubscription(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSubscription, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
