name: Security Audit

on:
  schedule:
    # 毎週日曜日の午前2時（UTC）に実行
    - cron: '0 2 * * 0'
  workflow_dispatch:
  push:
    branches: [ main, develop ]
    paths:
      - 'pubspec.yaml'
      - 'pubspec.lock'

jobs:
  security-audit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.2'
        cache: true
        
    - name: Configure Flutter
      run: |
        flutter config --no-analytics
        flutter config --no-cli-animations
        
    - name: Get dependencies
      run: flutter pub get
      
    - name: Run security audit
      run: |
        echo "Running dependency security audit..."
        flutter pub deps --json > deps.json
        cat deps.json
        
    - name: Check for known vulnerabilities
      run: |
        echo "Checking for known security vulnerabilities..."
        # pubspec.lockファイルをチェック
        if [ -f pubspec.lock ]; then
          echo "Dependencies found in pubspec.lock:"
          grep -E "dependency:|version:" pubspec.lock || true
        fi
        
    - name: Upload audit results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: security-audit-results
        path: |
          deps.json
          pubspec.lock
        retention-days: 30
